### ISSUE TITLE
Saving Issues

### ISSUE THREAD

**Issue by reesekneeland** [jayantsharma/salt#1]
The nature of the program is to only save the annotations created once the video completes, however this can cause a number of issues, if the program crashes, you lose al data and annotations as they are never saved. If you make a mistake and need to edit it, you cant without restarting the video as loading it into the program erases all existing annotations, and you have to redo the whole video. This makes it impossible to fix or add to any existing annotations without redoing all of the work,

**Comment by jayantsharma** [comment]
Recent commits partly resolve this by:

1. Dropping into review mode at end of playback and quitting only on manual prompt.
2. Improved memory management protects against crashes. However, save & restart feature is unavailable for the moment.
